# Parse all files with TypeScript.
extends: "standard-with-typescript"
parserOptions:
  project: "./tsconfig.json"
  createDefaultProgram: true

plugins:
  - prettier
  - react
  - jest
  - jest-dom
  - "@typescript-eslint"
  - react-hooks

settings:
  react:
    version: detect

env:
  browser: true

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  semi: 0
  comma-dangle: ["error", "always-multiline"]
  "@typescript-eslint/semi": ["error", "always"]
  "@typescript-eslint/no-floating-promises": 
    - error
    - ignoreIIFE: true

  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _
